baseurl: "https://planandlearn.net/"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Learning to Plan and Planning to Learn"
  Description: "Conference description"
  Date: "Date T.B.A"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Virtual"
  Address: "Boulevard Kukulcan, 30"
  City:  "Cancún"
  State: "Quintana"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - speakers
    - schedule
    - organizers

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    speakers: "Speakers"
    schedule: "Schedule"
    organizers: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "http://register.example.com"

  About:
    text1: "Planning and learning are two crucial capabilities of robots. While planning seeks to solve a task by synthesizing policies on the fly, learning seeks to obtain solutions from experiences provided by data. The two domains have independently advanced in the past decades and both achieved remarkable success on their most suitable tasks. There is a noticeable trend to combine these two capabilities. Impressive success has been demonstrated by AlphaZero and MuZero, showing that the integration of planning and learning can advance human-level intelligence. Particularly, there are two complementary directions: learning to plan and planning to learn. From the perspective of planning, there are important attempts seeking to learn sampling distributions, action abstractions, heuristics, and representations for planning. From the perspective of learning, there are prominent efforts to enable active and uncertainty-aware learning, and to incorporate existing models to augment learning and achieve sample-efficiency. However, what is missing is a systematic discussion on where and how these two strategies shall be best applied and how they can be seamlessly integrated."
    text2: "In this workshop, we aim to bring together researchers in the planning and learning sub-domains, to discuss opportunities to integrate them — by planning to learn and learning to plan— and to incubate the next level of intelligence. Particularly, we will discuss what and how to learn for planning, what and how to plan for learning, as well as principled choices and combinations between these two."
    text3: "Some questions we would like to highlight:"

  # The entire schedule
  Schedule:
    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      presentation:
        title: "Placeholder title"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"

    - name: "Leslie Kaelbling"
      photo: "/img/LeslieKaelbling.png"
      company: "Massachusetts Institute of Technology (MIT)"
      presentation:
        title: "Placeholder title"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "11h00"

    - name: "Siddhartha Srinivasa"
      photo: "/img/SiddharthaSrinivasa.png"
      company: "University of Washington (UW)"
      presentation:
        title: "Placeholder title"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

    - name: "Aleksandra Faust"
      photo: "/img/AleksandraFaust.png"
      company: "Google Brain"
      presentation:
        title: "Placeholder title"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

  Organizers:

    - name: "Panpan Cai"
      photo: "/img/PanpanCai.png"
      bio: "Panpan CAI is a postdoctoral research fellow at the National University of Singapore, working with David Hsu on integrated planning and learning, planning under uncertainty, and their applications on autonomous driving in crowded environments. She received her Ph.D. with Cai Yiyu and Zheng Jianmin at Nanyang Technological University. Panpan’s vision is to develop robots that can combine reasoning and learning to seamlessly interact with large-scale, dynamic, and interactive environments and accomplish challenging tasks."
      company: "National University of Singapore (NUS)"
      href: "https://cindycia.github.io/"

    - name: "Peter Karkus"
      photo: "/img/PeterKarkus.png"
      bio: "Peter Karkus is a PhD candidate at the National University of Singapore advised by Prof. David Hsu. He has previously spent time at MIT as a visiting researcher and at Google and DeepMind as a research intern. Peter's vision is to build human-level robot intelligence by combining structure and reasoning with learning. Peter's recent works are on neural networks that encode differentiable robot algorithms in order to learn partially observable planning, visual navigation, mapping and localization tasks. His work has been recognized by a number of awards, including a Fulbright scholarship, NUS research achievement awards, and best paper nominations."
      company: "National University of Singapore (NUS)"
      href: "http://karkus.tilda.ws/"

    - name: "GilWoo Lee"
      photo: "/img/GilWooLee.png"
      bio: "T.B.A"
      company: "University of Washington (UW)"
      href: "https://gilwoolee.github.io/"

    - name: "Yiyuan Lee"
      photo: "/img/YiyuanLee.png"
      bio: "T.B.A"
      company: "National University of Singapore (NUS)"
      href: "https://leeyiyuan.info/"

    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      bio: "David Hsu is a Provost's Chair Professor in the Department of computer science, National University of Singapore (NUS). He received PhD in computer science from Stanford University. His recent research interests include robot planning and learning under uncertainty and human-robot collaboration."
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"
