baseurl: "https://planandlearn.net/"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: ""

params:
  # Conference info
  Date: "Date T.B.A"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - overview
    - speakers
    - topics
    - callforcontributions
    - schedule
    - organizers
    - contact

  # Titles which you can translate to other languages
  Titles:
    overview: "Overview"
    speakers: "Speakers"
    topics: "Discussions"
    callforcontributions: "Submission"
    schedule: "Schedule"
    organizers: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Submit a Contribution"
    link: "#callforcontributions"

  # Speakers
  Speakers:
    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"

    - name: "Leslie Kaelbling"
      photo: "/img/LeslieKaelbling.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://people.csail.mit.edu/lpk/"

    - name: "Siddhartha Srinivasa"
      photo: "/img/SiddharthaSrinivasa.png"
      company: "University of Washington (UW)"
      href: "https://goodrobot.ai/"

    - name: "Nicholas Roy"
      photo: "/img/NicholasRoy.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "https://aeroastro.mit.edu/faculty-research/faculty-list/nicholas-roy"

    - name: "Alberto Rodriguez"
      photo: "/img/AlbertoRodriguez.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://meche.mit.edu/people/faculty/ALBERTOR@MIT.EDU"

    - name: "Aviv Tamar"
      photo: "/img/AvivTamar.png"
      company: "Israel Institute for Technology"
      href: "https://avivt.github.io/avivt/"

    - name: "Aleksandra Faust"
      photo: "/img/AleksandraFaust.png"
      company: "Google Brain"
      href: "https://www.afaust.info/"

    - name: "George Konidaris"
      photo: "/img/GeorgeKonidaris.png"
      company: "Brown University"
      href: "https://cs.brown.edu/~gdk/"

    - name: "Igor Mordatch"
      photo: "/img/IgorMordatch.png"
      company: "Google Brain"
      href: "https://scholar.google.com/citations?user=Vzr1RukAAAAJ"

    - name: "Andreas Geiger"
      photo: "/img/AndreasGeiger.png"
      company: "University of Tübingen"
      href: "http://www.cvlibs.net/"

    - name: "Michael Posa"
      photo: "/img/MichaelPosa.png"
      company: "University of Pennsylvania"
      href: "https://dair.seas.upenn.edu/michael-posa/"

    - name: "Amy Zhang"
      photo: "/img/AmyZhang.png"
      company: "McGill University"
      href: "https://amyzhang.github.io/"

    - name: "Dieter Fox"
      photo: "/img/DieterFox.png"
      company: "University of Washington "
      href: "https://homes.cs.washington.edu/~fox/"

    - name: "Chelsea Finn"
      photo: "/img/ChelseaFinn.png"
      company: "Stanford University"
      href: "https://ai.stanford.edu/~cbfinn/"


  Schedules:
    - timePdt: "06:55 - 07:00"
      timeCest: "15:55 - 16:00"
      timeSgt: "21:55 - 22:00"
      participants:
        - photo: "/img/PanpanCai.png"
          name: "Panpan Cai"
        - photo: "/img/DannyDriess.png"
          name: "Danny Driess"
      description: "Opening Remarks"

    - timePdt: "07:00 - 08:10"
      timeCest: "16:00 - 17:10"
      timeSgt: "22:00 - 23:10"
      participants:
        - photo: "/img/LeslieKaelbling.png"
          name: "Leslie Kaelbling"
        - photo: "/img/DieterFox.png"
          name: "Dieter Fox"
        - photo: "/img/ChelseaFinn.png"
          name: "Chelsea Finn"
        - photo: "/img/DavidHsu.png"
          name: "David Hsu"
      moderator:
          photo: "/img/MarcToussaint.png"
          name: "Marc Toussaint"
      description: "Moderated Panel I"

    - timePdt: "08:10 - 08:20"
      timeCest: "17:10 - 17:20"
      timeSgt: "23:10 - 23:20"
      participantstext: "Accepted abstracts"
      description: "Spotlight Talks"

    - timePdt: "08:20 - 09:30"
      timeCest: "17:20 - 18:30"
      timeSgt: "23:20 - 00:30"
      participants:
        - photo: "/img/AlbertoRodriguez.png"
          name: "Alberto Rodriguez"
        - photo: "/img/AvivTamar.png"
          name: "Aviv Tamar"
        - photo: "/img/AleksandraFaust.png"
          name: "Aleksandra Faust"
        - photo: "/img/GeorgeKonidaris.png"
          name: "George Konidaris"
        - photo: "/img/SiddharthaSrinivasa.png"
          name: "Siddhartha Srinivasa"
      moderator:
          photo: "/img/PanpanCai.png"
          name: "Panpan Cai"

      moderatorName: "Panpan Cai"
      description: "Moderated Panel II"

    - timePdt: "09:30 - 09:40"
      timeCest: "18:30 - 18:40"
      timeSgt: "00:30 - 00:40"
      participantstext: "Accepted abstracts"
      description: "Spotlight Talks"

    - timePdt: "09:40 - 10:50"
      timeCest: "18:40 - 19:50"
      timeSgt: "00:40 - 01:50"
      participants:
        - photo: "/img/IgorMordatch.png"
          name: "Igor Mordatch"
        - photo: "/img/MichaelPosa.png"
          name: "Michael Posa"
        - photo: "/img/AmyZhang.png"
          name: "Amy Zhang"
        - photo: "/img/AndreasGeiger.png"
          name: "Andreas Geiger"
        - photo: "/img/NicholasRoy.png"
          name: "Nicholas Roy"
      moderator:
          photo: "/img/DannyDriess.png"
          name: "Danny Driess"
      description: "Moderated panel III"

    - timePdt: "10:50 Onwards"
      timeCest: "19:50 Onwards"
      timeSgt: "01:50 Onwards"
      participantstext: "All participants"
      description: "Poster and Social Sessions"


  Organizers:
    - name: "Panpan Cai*"
      photo: "/img/PanpanCai.png"
      company: "National University of Singapore (NUS)"
      href: "https://cindycia.github.io/"

    - name: "Danny Driess*"
      photo: "/img/DannyDriess.png"
      company: "TU Berlin"
      href: "https://dannydriess.github.io/"

    - name: "Peter Karkus"
      photo: "/img/PeterKarkus.png"
      company: "National University of Singapore (NUS)"
      href: "http://karkus.tilda.ws/"

    - name: "Gilwoo Lee"
      photo: "/img/GilwooLee.png"
      company: "Zordi, Inc."
      href: "http://leegilwoo.com/"

    - name: "Yiyuan Lee"
      photo: "/img/YiyuanLee.png"
      company: "National University of Singapore (NUS)"
      href: "https://leeyiyuan.info"

    - name: "Jeannette Bohg"
      photo: "/img/JeannetteBohg.png"
      company: "Stanford University"
      href: "https://web.stanford.edu/~bohg/"

    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"

    - name: "Russ Tedrake"
      photo: "/img/RussTedrake.png"
      company: "Massachusetts Institute of Technology"
      href: "https://groups.csail.mit.edu/locomotion/russt.html"

    - name: "Marc Toussaint"
      photo: "/img/MarcToussaint.png"
      company: "TU Berlin"
      href: "http://www.marc-toussaint.net/"
