baseurl: "https://planandlearn.net/"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: "UA-68147157-8"

params:
  # Conference info
  Date: "July 12, 2021"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - overview
    - speakers
    - topics
    - callforcontributions
    - schedule
    - organizers
    - contact

  # Titles which you can translate to other languages
  Titles:
    overview: "Overview"
    speakers: "Speakers"
    topics: "Discussions"
    callforcontributions: "Submission"
    schedule: "Schedule"
    organizers: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Submit a Contribution"
    link: "#callforcontributions"

  # Speakers
  Speakers:
    - name: "Aleksandra Faust"
      photo: "/img/AleksandraFaust.png"
      company: "Google Brain"
      href: "https://www.afaust.info/"

    - name: "Chelsea Finn"
      photo: "/img/ChelseaFinn.png"
      company: "Stanford University"
      href: "https://ai.stanford.edu/~cbfinn/"

    - name: "Dieter Fox"
      photo: "/img/DieterFox.png"
      company: "University of Washington "
      href: "https://homes.cs.washington.edu/~fox/"

    - name: "Andreas Geiger"
      photo: "/img/AndreasGeiger.png"
      company: "University of Tübingen"
      href: "http://www.cvlibs.net/"

    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"

    - name: "Leslie Kaelbling"
      photo: "/img/LeslieKaelbling.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://people.csail.mit.edu/lpk/"

    - name: "George Konidaris"
      photo: "/img/GeorgeKonidaris.png"
      company: "Brown University"
      href: "https://cs.brown.edu/~gdk/"

    - name: "Igor Mordatch"
      photo: "/img/IgorMordatch.png"
      company: "Google Brain"
      href: "https://scholar.google.com/citations?user=Vzr1RukAAAAJ"

    - name: "Michael Posa"
      photo: "/img/MichaelPosa.png"
      company: "University of Pennsylvania"
      href: "https://dair.seas.upenn.edu/michael-posa/"

    - name: "Alberto Rodriguez"
      photo: "/img/AlbertoRodriguez.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://meche.mit.edu/people/faculty/ALBERTOR@MIT.EDU"

    - name: "Nicholas Roy"
      photo: "/img/NicholasRoy.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "https://aeroastro.mit.edu/faculty-research/faculty-list/nicholas-roy"

    - name: "Siddhartha Srinivasa"
      photo: "/img/SiddharthaSrinivasa.png"
      company: "University of Washington (UW)"
      href: "https://goodrobot.ai/"

    - name: "Aviv Tamar"
      photo: "/img/AvivTamar.png"
      company: "Israel Institute for Technology"
      href: "https://avivt.github.io/avivt/"

    - name: "Amy Zhang"
      photo: "/img/AmyZhang.png"
      company: "McGill University"
      href: "https://amyzhang.github.io/"


  Schedules:

    - timePdt: "10:00 - 11:30"
      timeCest: "19:00 - 20:30"
      timeSgt: "01:00 - 02:30"
      participants:
        - photo: "/img/AleksandraFaust.png"
          name: "Aleksandra Faust"
        - photo: "/img/GeorgeKonidaris.png"
          name: "George Konidaris"
        - photo: "/img/AlbertoRodriguez.png"
          name: "Alberto Rodriguez"
        - photo: "/img/SiddharthaSrinivasa.png"
          name: "Siddhartha Srinivasa"
        - photo: "/img/AvivTamar.png"
          name: "Aviv Tamar"
      moderator:
          photo: "/img/PanpanCai.png"
          name: "Panpan Cai"
      description: "Moderated Panel I"

    - timePdt: "11:40 - 13:10"
      timeCest: "20:40 - 22:10"
      timeSgt: "02:40 - 04:10"
      participants:
        - photo: "/img/AndreasGeiger.png"
          name: "Andreas Geiger"
        - photo: "/img/IgorMordatch.png"
          name: "Igor Mordatch"
        - photo: "/img/MichaelPosa.png"
          name: "Michael Posa"
        - photo: "/img/NicholasRoy.png"
          name: "Nicholas Roy"
        - photo: "/img/AmyZhang.png"
          name: "Amy Zhang"
      moderator:
          photo: "/img/DannyDriess.png"
          name: "Danny Driess"
      description: "Moderated Panel II"

    - timePdt: "13:10 - 13:30"
      timeCest: "22:10 - 22:30"
      timeSgt: "04:10 - 04:30"
      participantstext: "Accepted abstracts"
      description: "Spotlight Talks (Group 1)"

    - timePdt: "13:30 - 17:00"
      timeCest: "22:30 - 02:00"
      timeSgt: "04:30 - 08:00"
      participantstext: "All participants"
      description: "Poster and Social Sessions"

    - timePdt: "17:00 - 18:30"
      timeCest: "02:00 - 03:30"
      timeSgt: "08:00 - 08:30"
      participants:
        - photo: "/img/ChelseaFinn.png"
          name: "Chelsea Finn"
        - photo: "/img/DieterFox.png"
          name: "Dieter Fox"
        - photo: "/img/DavidHsu.png"
          name: "David Hsu"
        - photo: "/img/LeslieKaelbling.png"
          name: "Leslie Kaelbling"
      moderator:
          photo: "/img/RussTedrake.png"
          name: "Russ Tedrake"
      description: "Moderated panel III"

    - timePdt: "18:30 - 18:50"
      timeCest: "03:30 - 03:50"
      timeSgt: "09:30 - 09:50"
      participantstext: "Accepted abstracts"
      description: "Spotlight Talks (Group 2)"

    - timePdt: "18:50 onwards"
      timeCest: "03:50 onwards"
      timeSgt: "09:50 onwards"
      participantstext: "All participants"
      description: "Poster and Social Sessions"


  Organizers:
    - name: "Panpan Cai*"
      photo: "/img/PanpanCai.png"
      company: "National University of Singapore (NUS)"
      href: "https://cindycia.github.io/"

    - name: "Danny Driess*"
      photo: "/img/DannyDriess.png"
      company: "TU Berlin"
      href: "https://dannydriess.github.io/"

    - name: "Peter Karkus"
      photo: "/img/PeterKarkus.png"
      company: "National University of Singapore (NUS)"
      href: "http://karkus.tilda.ws/"

    - name: "Gilwoo Lee"
      photo: "/img/GilwooLee.png"
      company: "Zordi, Inc."
      href: "http://leegilwoo.com/"

    - name: "Yiyuan Lee"
      photo: "/img/YiyuanLee.png"
      company: "National University of Singapore (NUS)"
      href: "https://leeyiyuan.info"

    - name: "Jeannette Bohg"
      photo: "/img/JeannetteBohg.png"
      company: "Stanford University"
      href: "https://web.stanford.edu/~bohg/"

    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"

    - name: "Russ Tedrake"
      photo: "/img/RussTedrake.png"
      company: "Massachusetts Institute of Technology"
      href: "https://groups.csail.mit.edu/locomotion/russt.html"

    - name: "Marc Toussaint"
      photo: "/img/MarcToussaint.png"
      company: "TU Berlin"
      href: "http://www.marc-toussaint.net/"
