baseurl: "https://planandlearn.net/"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "RSS 2021 Workshop on Learning to Plan and Planning to Learn"
  Description: "Conference description"
  Date: "Date T.B.A"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - overview
    - speakers
    - topics
    - callforcontributions
    - schedule
    - organizers
    - contact

  # Titles which you can translate to other languages
  Titles:
    overview: "Overview"
    speakers: "Speakers"
    topics: "Discussions"
    callforcontributions: "Submissions"
    schedule: "Schedule"
    organizers: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Submit a Contribution"
    link: "#callforcontributions"

  # Speakers
  Speakers:
    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"

    - name: "Leslie Kaelbling"
      photo: "/img/LeslieKaelbling.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://people.csail.mit.edu/lpk/"

    - name: "Siddhartha Srinivasa"
      photo: "/img/SiddharthaSrinivasa.png"
      company: "University of Washington (UW)"
      href: "https://goodrobot.ai/"

    - name: "Aleksandra Faust"
      photo: "/img/AleksandraFaust.png"
      company: "Google Brain"
      href: " https://www.afaust.info/"

  Schedules:
    - time: "07:55 - 08:00"
      participants:
        - photo: "/img/PanpanCai.png"
      description: "Opening Remarks"

    - time: "08:00 - 09:20"
      participants:
        - photo: "/img/DavidHsu.png"
        - photo: "/img/LeslieKaelbling.png"
        - photo: "/img/SiddharthaSrinivasa.png"
        - photo: "/img/AleksandraFaust.png"
        - photo: "/img/PanpanCai.png"
      description: "Moderated panel: \"LPPL: what, where, and how?\""

    - time: "09:20 - 09:50"
      participantstext: "Accepted abstracts"
      description: "Contributed spotlight talks (2-mins each)"

    - time: "09:50 - 11:10"
      participants:
        - photo: "/img/DavidHsu.png"
        - photo: "/img/LeslieKaelbling.png"
        - photo: "/img/SiddharthaSrinivasa.png"
        - photo: "/img/AleksandraFaust.png"
        - photo: "/img/PanpanCai.png"
      description: "Moderated panel: \"LPPL: retrospects and prospects.\""
    - time: "11:10 - 12:10"
      participantstext: "All participants"
      description: "Virtual poster sessions at Gather.town"

    - time: "12:10 Onwards"
      participantstext: "All participants"
      description: "Virtual coffee time at Gather.town"


  Organizers:
    - name: "Panpan Cai"
      photo: "/img/PanpanCai.png"
      bio: "Panpan CAI is a postdoctoral research fellow at the National University of Singapore, working with David Hsu on integrated planning and learning, planning under uncertainty, and their applications on autonomous driving in crowded environments. She received her Ph.D. with Cai Yiyu and Zheng Jianmin at Nanyang Technological University. Panpan’s vision is to develop robots that can combine reasoning and learning to seamlessly interact with large-scale, dynamic, and interactive environments and accomplish challenging tasks."
      company: "National University of Singapore (NUS)"
      href: "https://cindycia.github.io/"

    - name: "Peter Karkus"
      photo: "/img/PeterKarkus.png"
      bio: "Peter Karkus is a PhD candidate at the National University of Singapore advised by Prof. David Hsu. He has previously spent time at MIT as a visiting researcher and at Google and DeepMind as a research intern. Peter's vision is to build human-level robot intelligence by combining structure and reasoning with learning. Peter's recent works are on neural networks that encode differentiable robot algorithms in order to learn partially observable planning, visual navigation, mapping and localization tasks. His work has been recognized by a number of awards, including a Fulbright scholarship, NUS research achievement awards, and best paper nominations."
      company: "National University of Singapore (NUS)"
      href: "http://karkus.tilda.ws/"

    - name: "Gilwoo Lee"
      photo: "/img/GilwooLee.png"
      bio: "Gilwoo Lee is the founder CEO of Zordi, Inc., an agricultural startup focusing on controlled environment agriculture. Lee has received her Ph.D. degree from the University of Washington, where she was advised by Siddhartha S. Srinivasa. She has worked on Bayesian Reinforcement Learning, learning and planning under uncertainty, and human-robot interaction, with applications ranging from assistive robots to mobile racecars."
      company: "Zordi, Inc."
      href: "http://leegilwoo.com/"

    - name: "Yiyuan Lee"
      photo: "/img/YiyuanLee.png"
      bio: "Yiyuan Lee is an undergraduate researcher at the National University of Singapore, advised by Prof. David Hsu. He will be joining Rice University as a graduate student to work with Prof. Lydia Kavraki and Prof. Kaiyu Hang. His current interests lie in using learning to improve model-based planning for robotics tasks, particularly for planning under uncertainty. Previously, he has worked on systems for autonomous driving, including a real-world autonomous scooter as well as a simulator platform for autonomous driving in crowded environments."
      company: "National University of Singapore (NUS)"
      href: "https://leeyiyuan.info"

    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      bio: "David Hsu is a Provost's Chair Professor in the Department of computer science, National University of Singapore (NUS). He received Ph.D. in computer science from Stanford University. At NUS, he co-founded NUS Advanced Robotics Center in 2013 and founded the NUS AI Laboratory (NUSAIL) in the School of Computing in 2019. He held visiting positions in MIT Aeronautics & Astronautics Department and CMU Robotics Institue. He is an IEEE Fellow. His research interests span robotics, AI, and computational structural biology. In recent years, he has been working on robot planning and learning under uncertainty and human-robot collaboration."
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"
