baseurl: "https://planandlearn.net/"
title: "RSS 2021 Workshop on Integrating Planning and Learning"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: "UA-68147157-8"

params:
  # Conference info
  Name: "RSS 2021 Workshop on Integrating Planning and Learning"
  Description: "RSS 2021 Workshop on Integrating Planning and Learning"
  Date: "July 12, 2021"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - overview
    - speakers
    - topics
    - schedule
    - callforcontributions
    - organizers
    - contact

  # Titles which you can translate to other languages
  Titles:
    overview: "Overview"
    speakers: "Speakers"
    topics: "Discussions"
    callforcontributions: "Accepted Contributions"
    schedule: "Schedule"
    organizers: "Organizers"
    contact: "Contact"

  # Speakers
  Speakers:
    - name: "Aleksandra Faust"
      photo: "/img/AleksandraFaust.png"
      company: "Google Brain"
      href: "https://www.afaust.info/"

    - name: "Chelsea Finn"
      photo: "/img/ChelseaFinn.png"
      company: "Stanford University"
      href: "https://ai.stanford.edu/~cbfinn/"

    - name: "Dieter Fox"
      photo: "/img/DieterFox.png"
      company: "University of Washington "
      href: "https://homes.cs.washington.edu/~fox/"

    - name: "David Hsu"
      photo: "/img/DavidHsu.png"
      company: "National University of Singapore (NUS)"
      href: "https://www.comp.nus.edu.sg/~dyhsu/"

    - name: "Leslie Kaelbling"
      photo: "/img/LeslieKaelbling.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://people.csail.mit.edu/lpk/"

    - name: "George Konidaris"
      photo: "/img/GeorgeKonidaris.png"
      company: "Brown University"
      href: "https://cs.brown.edu/~gdk/"

    - name: "Igor Mordatch"
      photo: "/img/IgorMordatch.png"
      company: "Google Brain"
      href: "https://scholar.google.com/citations?user=Vzr1RukAAAAJ"

    - name: "Michael Posa"
      photo: "/img/MichaelPosa.png"
      company: "University of Pennsylvania"
      href: "https://dair.seas.upenn.edu/michael-posa/"

    - name: "Alberto Rodriguez"
      photo: "/img/AlbertoRodriguez.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "http://meche.mit.edu/people/faculty/ALBERTOR@MIT.EDU"

    - name: "Nicholas Roy"
      photo: "/img/NicholasRoy.png"
      company: "Massachusetts Institute of Technology (MIT)"
      href: "https://aeroastro.mit.edu/faculty-research/faculty-list/nicholas-roy"

    - name: "Aviv Tamar"
      photo: "/img/AvivTamar.png"
      company: "Israel Institute for Technology"
      href: "https://avivt.github.io/avivt/"

    - name: "Amy Zhang"
      photo: "/img/AmyZhang.png"
      company: "McGill University"
      href: "https://amyzhang.github.io/"

  contributions:
    - title: "Interaction Prediction and Monte-Carlo Tree Search for Robot Manipulation in Clutter"
      authors: "Baichuan Huang, Shuai D. Han, Abdeslam Boularias, Jingjin Yu"
      paperLink: "https://drive.google.com/file/d/1ZiohsZo7vjMkPMbT-iZxIBT0bjjPHUDK/view"
      videoLink: "https://drive.google.com/file/d/1AKL6BAFJHDRG1UccN4P966hxR6vYl4T2/view"

    - title: "Information-Theoretic Reward Shaping for Multimodal Object Attribute Learning"
      authors: "Xiaohan Zhang, Jivko Sinapov, Shiqi Zhang"
      paperLink: "https://drive.google.com/file/d/15q7wIJgJ_jvg80BGpQLopMfcczQnJ7gj/view"
      videoLink: "https://drive.google.com/file/d/1vcuSyu-Dy0EpJivcV5-glkPbfjZLlBhZ/view"

    - title: "Safe Exploration for Reinforcement Learning Using Unsupervised Action Planning"
      authors: "Hao-Lun Hsu, Qiuhua Huang, Sehoon Ha"
      paperLink: "https://drive.google.com/file/d/1yuh_CDFjzuT6f9hDcyeWwt3--dPuiPoH/view"
      videoLink: "https://drive.google.com/file/d/1jC83ozjUlpNBLrGJmQPKM95z3HNUIQTz/view"

    - title: "Imitation Learning-Based Path Generation for the Complex Assembly of Deformable Objects"
      authors: "Yitaek Kim, Christoffer Sloth"
      paperLink: "https://drive.google.com/file/d/1dIXgr6GQ45s5Cc_xjTVVUtO3--Mgokia/view"
      videoLink: "https://drive.google.com/file/d/1mKaNlXpq1skPR7eBnuD9UxJgd2cjQdwi/view"

    - title: "Integrated Commonsense Reasoning and Interactive Learning in Robotics"
      authors: "Mohan Sridharan"
      paperLink: "https://drive.google.com/file/d/1i8raaB5GMQXT129iQQiLZWSntyODU3zI/view"
      videoLink: "https://drive.google.com/file/d/1w-3ns1aUVGU3dN2DM_T_kpoUMzgIF0Hc/view"

    - title: "Adversarially Regularized Policy Learning Guided by Trajectory Optimization"
      authors: "Zhigen Zhao, Simiao Zuo, Tuo Zhao, Ye Zhao"
      paperLink: "https://drive.google.com/file/d/19LCyQmGUj1dUbprN-j4_7nkyzyK3r5CX/view"
      videoLink: "https://drive.google.com/file/d/1ihH7JwUZM0sFEHF7NP_26prGriqlDYYk/view"

    - title: "Gaussian Process Constraint Learning for Scalable Safe Motion Planning from Demonstrations"
      authors: "Hao Wang, Glen Chou, Dmitry Berenson"
      paperLink: "https://drive.google.com/file/d/1ltYApVQ7PmDYkDKad9rYotRLi3rv_vNM/view"
      videoLink: "https://drive.google.com/file/d/1IsEEQfKcQTjD0LEEQb6EgGcISV-LmvjK/view"

    - title: "Towards Safe, Abstraction-based Online Learning and Synthesis for Unknown Systems"
      authors: "John Jackson, Luca Laurenti, Eric W Frew, Morteza Lahijanian"
      paperLink: "https://drive.google.com/file/d/1XYq_O_7tLNYQmE7Gr2wx1N88P6OxLFii/view"
      videoLink: "https://drive.google.com/file/d/1ollYrtXSVvdt-LFGlA8O4IW3r4hdiCwB/view"

    - title: "Entropy Regularized Motion Planning via Stein Variational Inference"
      authors: "Alexander Lambert, Byron Boots"
      paperLink: "https://drive.google.com/file/d/1_t9H-sj0BhWXA5eMzsNV3gg3laVs9zRk/view"
      videoLink: "https://drive.google.com/file/d/13k_9-MkLnMgRtt0mI05a8FMUFqA_9bsj/view"

    - title: "Receding horizon inverse reinforcement learning"
      authors: "Wei Gao, Yiqing Xu, David Hsu"
      paperLink: "https://drive.google.com/file/d/1FoKy1kDyq-yWS5SgccAlpD7M6YauYpJQ/view"
      videoLink: "https://drive.google.com/file/d/1imHqN42PMOTbs1ve_4RGzTCsvp-yz30o/view"

  Schedules:

    - timePdt: "10:00 - 11:30"
      timePdtDetails: ", July 12"
      timeCest: "19:00 - 20:30"
      timeCestDetails: ", July 12"
      timeSgt: "01:00 - 02:30"
      timeSgtDetails: ", July 13"
      participants:
        - photo: "/img/AleksandraFaust.png"
          name: "Aleksandra Faust"
        - photo: "/img/GeorgeKonidaris.png"
          name: "George Konidaris"
        - photo: "/img/AlbertoRodriguez.png"
          name: "Alberto Rodriguez"
        - photo: "/img/AvivTamar.png"
          name: "Aviv Tamar"
      moderator:
          photo: "/img/PanpanCai.png"
          name: "Panpan Cai"
      description: "Moderated Panel I: Learning to plan, differentiable planner, and planning to learn."

    - timePdt: "11:40 - 13:10"
      timePdtDetails: ", July 12"
      timeCest: "20:40 - 22:10"
      timeCestDetails: ", July 12"
      timeSgt: "02:40 - 04:10"
      timeSgtDetails: ", July 13"
      participants:
        - photo: "/img/IgorMordatch.png"
          name: "Igor Mordatch"
        - photo: "/img/MichaelPosa.png"
          name: "Michael Posa"
        - photo: "/img/NicholasRoy.png"
          name: "Nicholas Roy"
        - photo: "/img/AmyZhang.png"
          name: "Amy Zhang"
      moderator:
          photo: "/img/DannyDriess.png"
          name: "Danny Driess"
      description: "Moderated Panel II: Model learning, learning representations, and model-augmented learning."

    - timePdt: "13:10 - 13:30"
      timePdtDetails: ", July 12"
      timeCest: "22:10 - 22:30"
      timeCestDetails: ", July 12"
      timeSgt: "04:10 - 04:30"
      timeSgtDetails: ", July 13"
      participantstext: "Accepted abstracts"
      description: "Spotlight Talks (Group 1)"

    - timePdt: "13:30 - 14:30"
      timePdtDetails: ", July 12"
      timeCest: "22:30 - 23:30"
      timeCestDetails: ", July 12"
      timeSgt: "04:30 - 05:30"
      timeSgtDetails: ", July 13"
      participantstext: "All participants"
      description: "Poster Session"

    - timePdt: "14:30 - 17:00"
      timePdtDetails: ", July 12"
      timeCest: "23:30 - 02:00"
      timeCestDetails: ", July 12-13"
      timeSgt: "05:30 - 08:00"
      timeSgtDetails: ", July 13"
      participantstext: "All participants"
      description: "Social Hang-out"

    - timePdt: "17:00 - 18:30"
      timePdtDetails: ", July 12"
      timeCest: "02:00 - 03:30"
      timeCestDetails: ", July 13"
      timeSgt: "08:00 - 09:30"
      timeSgtDetails: ", July 13"
      participants:
        - photo: "/img/ChelseaFinn.png"
          name: "Chelsea Finn"
        - photo: "/img/DieterFox.png"
          name: "Dieter Fox"
        - photo: "/img/DavidHsu.png"
          name: "David Hsu"
        - photo: "/img/LeslieKaelbling.png"
          name: "Leslie Kaelbling"
      moderator:
          photo: "/img/RussTedrake.png"
          name: "Russ Tedrake"
      description: "Moderated Panel III: New opportunities for integrating planning and learning."

    - timePdt: "18:30 - 18:50"
      timePdtDetails: ", July 12"
      timeCest: "03:30 - 03:50"
      timeCestDetails: ", July 13"
      timeSgt: "09:30 - 09:50"
      timeSgtDetails: ", July 13"
      participantstext: "Accepted abstracts"
      description: "Spotlight Talks (Group 2)"

    - timePdt: "18:50 - 19:50"
      timePdtDetails: ", July 12"
      timeCest: "03:50 - 04:50"
      timeCestDetails: ", July 13"
      timeSgt: "09:50 - 10:50"
      timeSgtDetails: ", July 13"
      participantstext: "All participants"
      description: "Poster Session"

    - timePdt: "19:50 onwards"
      timePdtDetails: ", July 12"
      timeCest: "04:50 onwards"
      timeCestDetails: ", July 13"
      timeSgt: "10:50 onwards"
      timeSgtDetails: ", July 13"
      participantstext: "All participants"
      description: "Social Hang-out"


  Organizers:
    - name: "Panpan Cai*"
      photo: "/img/PanpanCai.png"
      company: "National University of Singapore (NUS)"
      href: "https://cindycia.github.io/"

    - name: "Danny Driess*"
      photo: "/img/DannyDriess.png"
      company: "TU Berlin"
      href: "https://dannydriess.github.io/"

    - name: "Peter Karkus"
      photo: "/img/PeterKarkus.png"
      company: "National University of Singapore (NUS)"
      href: "http://karkus.tilda.ws/"

    - name: "Gilwoo Lee"
      photo: "/img/GilwooLee.png"
      company: "Zordi, Inc."
      href: "http://leegilwoo.com/"

    - name: "Yiyuan Lee"
      photo: "/img/YiyuanLee.png"
      company: "National University of Singapore (NUS)"
      href: "https://leeyiyuan.info"

    - name: "Oz S. Oguz"
      photo: "/img/OzSOguz.png"
      company: "Uni Stuttgart & Cluster of Exc. IntCDC"
      href: "https://oz-oguz.github.io"

    - name: "Jeannette Bohg"
      photo: "/img/JeannetteBohg.png"
      company: "Stanford University"
      href: "https://web.stanford.edu/~bohg/"

    - name: "Russ Tedrake"
      photo: "/img/RussTedrake.png"
      company: "Massachusetts Institute of Technology"
      href: "https://groups.csail.mit.edu/locomotion/russt.html"

    - name: "Marc Toussaint"
      photo: "/img/MarcToussaint.png"
      company: "TU Berlin"
      href: "http://www.marc-toussaint.net/"
